;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_gets
	.import		_printf
	.import		_puts
	.export		_main

.segment	"RODATA"

L0004:
	.byte	$45,$6E,$74,$65,$72,$20,$61,$20,$76,$61,$6C,$75,$65,$20,$3A,$00
L0009:
	.byte	$0A,$59,$6F,$75,$20,$65,$6E,$74,$65,$72,$65,$64,$3A,$20,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$64
	jsr     subysp
	lda     #<(L0004)
	ldx     #>(L0004)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     sp
	ldx     sp+1
	jsr     _gets
	lda     #<(L0009)
	ldx     #>(L0009)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     sp
	ldx     sp+1
	jsr     _puts
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	ldy     #$64
	jsr     addysp
	rts

.endproc

